// react-vs-vue/checkout-app-vue/src/App.vue
<template>
  <div id="app">
    <div class="products-list">
      <div class="products" v-for="(product,index) in products" :key="index">
        <h2>{{product.name}}: ${{product.price}}</h2>
        <button @click="addToCart(index);">Add to cart</button>
      </div>
    </div>

    <hr>
    <p>Cart Items</p>
    <p>Total price: ${{calculateTotalPrice()}}</p>
    <!-- Cart GOes here -->
    <div class="cart-list">
      <div class="products" v-for="(product,index) in cart" :key="index">
        <h2>{{product.name}}: ${{product.price}}</h2>
        <button @click="addToCart(index);">Add to cart</button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      products: [
        { name: "Shirt", price: 20 },
        { name: "Pants", price: 40 },
        { name: "Shoes", price: 60 },
        { name: "Hat", price: 20 }
      ],
      cart: []
    };
  },
  methods: {
    addToCart(index) {
      this.cart = this.cart.concat(this.products[index]);
    },
    calculateTotalPrice() {
      return this.cart.reduce((price, product) => price + product.price, 0);
    }
  }
};
</script>


<style scoped>
.products {
  padding: 20px;
  max-width: 300px;
  margin-bottom: 20px;
  border-radius: 5px;
  background-color: #fff;
  border: 1px solid #ddd;
}
</style>

// front-end-frameworks/react-vs-vue/checkout-app-react/src/App.js
import React, { useState } from "react";
import styled from "styled-components";

function Product({ product, children }) {
  return (
    <StyledProducts>
      <h2>
        {product.name}: ${product.price}
      </h2>
      {children}
    </StyledProducts>
  );
}

function App() {
  const [products, setProducts] = useState([
    { name: "Shirt", price: 20 },
    { name: "Pants", price: 40 },
    { name: "Shoes", price: 60 },
    { name: "Hat", price: 20 }
  ]);

  const [cart, setCart] = useState([]);

  const addToCart = index => setCart(cart.concat(products[index]));

  const calculateTotalPrice = () =>
    cart.reduce((price, product) => price + product.price, 0);

  return (
    <div className="App">
      {products.map((product, index) => (
        <Product product={product}>
          <button onClick={() => addToCart(index)}>Add to cart</button>
        </Product>
      ))}
      <hr />
      <p>Cart Items</p>
      <p> Total price: ${calculateTotalPrice()}</p>
      {cart.map(product => (
        <Product product={product} />
      ))}
    </div>
  );
}

const StyledProducts = styled.div`
  padding: 20px;
  max-width: 300px;
  border-radius: 5px;
  margin-bottom: 20px;
  border: 1px solid #ddd;
`;
export default App;
